const pokeDatos = [
  {
    id: "001",
    name: "Bulbasaur",
    image: "/images/bulbasaur.png",
    color: "#74CB48",
    secondary_color: "#A43E9E",
    main_type: "Grass",
    secondary_type: "Poison",
    main_ability: "Chlorophyll",
    secondary_ability: "Overgrow",
    height: "0,7 m",
    weight: "6,9 kg",
    description:
      "There is a plant seed on its back right from the day this Pokemon is born. The seed slowly grows larger.",
    stats: {
      HP: 45,
      ATK: 49,
      DEF: 49,
      SATK: 65,
      SDEF: 65,
      SPD: 45,
    },
  },
  {
    id: "004",
    name: "Charmander",
    image: "/images/charmander.png",
    color: "#f57d31",
    secondary_color: "",
    main_type: "Fire",
    main_ability: "Mega Punch",
    secondary_ability: "Fire Punch",
    height: "0,6 m",
    weight: "8,5 kg",
    description:
      "It has a preference for hot things. When it rains, steam is said to spout from the tip of its tail.",
    stats: {
      HP: 39,
      ATK: 52,
      DEF: 43,
      SATK: 60,
      SDEF: 50,
      SPD: 65,
    },
  },
  {
    id: "007",
    name: "Squirtle",
    image: "/images/squirtle.png",
    color: "#6493eb",
    secondary_color: "",
    main_type: "Water",
    main_ability: "Torrent",
    secondary_ability: "Rain Dish",
    height: "0,5 m",
    weight: "9,0 kg",
    description:
      "When it retracts its long neck into its shell, it squirts out water with vigorous force.",
    stats: {
      HP: 44,
      ATK: 48,
      DEF: 65,
      SATK: 50,
      SDEF: 64,
      SPD: 43,
    },
  },
  {
    id: "012",
    name: "Butterfree",
    image: "/images/butterfree.png",
    color: "#a7b723",
    secondary_color: "#A891ec",
    main_type: "Bug",
    secondary_type: "Flying",
    main_ability: "Compound Eyes",
    secondary_ability: "Tinted Lens",
    height: "1,1 m",
    weight: "32,0 kg",
    description:
      "In battle, it flaps its wings at high speed to release highly toxic dust into the air.",
    stats: {
      HP: 60,
      ATK: 45,
      DEF: 50,
      SATK: 90,
      SDEF: 80,
      SPD: 70,
    },
  },
  {
    id: "016",
    name: "Pidgey",
    image: "/images/pidgey.PNG",
    color: "#A891ec",
    secondary_color: "#aaa67f",
    main_type: "Flying",
    secondary_type: "Normal",
    main_ability: "Keen Eye",
    secondary_ability: "Tangled Feet",
    height: "0,3 m",
    weight: "1,8 kg",
    description:
      "A common sight in forests and woods. It flaps its wings at ground level to kick up blinding sand.",
    stats: {
      HP: 40,
      ATK: 45,
      DEF: 40,
      SATK: 35,
      SDEF: 35,
      SPD: 56,
    },
  },
  {
    id: "025",
    name: "Pikachu",
    image: "/images/pikachu.png",
    color: "#f9cf30",
    secondary_color: "",
    main_type: "Electrical",
    secondary_type: "",
    main_ability: "Static",
    secondary_ability: "Lightning Rod",
    height: "0,4 m",
    weight: "6,0 kg",
    description:
      "Pikachu that can generate powerful electricity have cheek sacs that are extra soft and super stretchy.",
    stats: {
      HP: 35,
      ATK: 55,
      DEF: 40,
      SATK: 50,
      SDEF: 50,
      SPD: 90,
    },
  },
  {
    id: "035",
    name: "Clefairy",
    image: "/images/clefairy.png",
    color: "#E69EAC",
    secondary_color: "",
    main_type: "Fairy",
    secondary_type: "",
    main_ability: "Cute Charm",
    secondary_ability: "Magic Guard",
    height: "0,6 m",
    weight: "7,5 kg",
    description:
      "Adored for their cute looks and playfulness. They are thought to be rare, as they do not appear often.",
    stats: {
      HP: 70,
      ATK: 45,
      DEF: 48,
      SATK: 60,
      SDEF: 65,
      SPD: 35,
    },
  },
  {
    id: "066",
    name: "Machop",
    image: "/images/machop.png",
    color: "#c12239",
    secondary_color: "",
    main_type: "Fighting",
    secondary_type: "",
    main_ability: "Guts",
    secondary_ability: "No Guard",
    height: "0,8 m",
    weight: "19,5 kg",
    description:
      "Loves to build its muscles. It trains in all styles of martial arts to become even stronger.",
    stats: {
      HP: 70,
      ATK: 80,
      DEF: 50,
      SATK: 35,
      SDEF: 35,
      SPD: 35,
    },
  },
  {
    id: "092",
    name: "Gastly",
    image: "/images/gastly.png",
    color: "#70559B",
    secondary_color: "#A43E9E",
    main_type: "Ghost",
    secondary_type: "Poison",
    main_ability: "Levitate",
    secondary_ability: "",
    height: "1,3 m",
    weight: "0,1 kg",
    description:
      "Born from gases, anyone would faint if engulfed by its gaseous body, which contains poison.",
    stats: {
      HP: 30,
      ATK: 35,
      DEF: 30,
      SATK: 100,
      SDEF: 35,
      SPD: 80,
    },
  },
  {
    id: "132",
    name: "Ditto",
    image: "/images/ditto.png",
    color: "#aaa67f",
    secondary_color: "",
    main_type: "Normal",
    secondary_type: "",
    main_ability: "Limber",
    secondary_ability: "Imposter",
    height: "0,3 m",
    weight: "4,0 kg",
    description:
      "It can reconstitute its entire cellular structure to change into what it sees, but it returns to normal when it relaxes.",
    stats: {
      HP: 48,
      ATK: 48,
      DEF: 48,
      SATK: 48,
      SDEF: 48,
      SPD: 48,
    },
  },
  {
    id: "151",
    name: "Mew",
    image: "/images/mew.png",
    color: "#fb5584",
    secondary_color: "",
    main_type: "Psychic",
    secondary_type: "",
    main_ability: "Synchronize",
    secondary_ability: "",
    height: "0,4 m",
    weight: "4,0 kg",
    description:
      "When viewed through a microscope, this Pokemon's short, fine, delicate hair can be seen.",
    stats: {
      HP: 100,
      ATK: 100,
      DEF: 100,
      SATK: 100,
      SDEF: 100,
      SPD: 100,
    },
  },
  {
    id: "304",
    name: "Aron",
    image: "/images/aron.png",
    color: "#b789d0",
    secondary_color: "#B69E31",
    main_type: "Steel",
    secondary_type: "Rock",
    main_ability: "Sturdy",
    secondary_ability: "Rock Head",
    height: "0,4 m",
    weight: "60,0 kg",
    description:
      "It eats iron ore—and sometimes railroad tracks—to build up the steel armor that protects its body.",
    stats: {
      HP: 50,
      ATK: 70,
      DEF: 100,
      SATK: 40,
      SDEF: 40,
      SPD: 30,
    },
  },
];
export default pokeDatos;
